function [features,varNames] = feature_extraction(f)
% FEATURE_EXTRACTION is code ported from PETRAE paper classification
%    Thrasyvoulos Karydis
%    04/15/2015
%    (c) Massachusetts Institute of Technology 2015
%    Permission granted for experimental and personal use;
%    license for commercial sale available from MIT

k = 1;

% varNames = {'label', ...
%             'alpha_LE' ,'alpha_LF' ,'alpha_RF'  ,'alpha_RE', ...
%             'beta_LE'  ,'beta_LF'  ,'beta_RF'   ,'beta_RE' , ...
%             'gamma_LE','gamma_LF','gamma_RF','gamma_RE', ...
%             'delta_LE','delta_LF','delta_RF','delta_RE', ...
%             'theta_LE','theta_LF','theta_RF','theta_RE' };

%optimal
varNames = {'label', ...
            'alpha_RF', ...
            'beta_LE'  ,'beta_LF' , ...
            'gamma_LE','gamma_LF','gamma_RF', ...
            'theta_LE'};
        
observations = [];
    
%optimal: 3     5     6    10    11    12    17
for t=1:size(f.alpha,2)        
     if (~strcmp(f.label{t},'unknown'))
        response{k} = f.label{t};           %#ok<AGROW>
%         row = [f.alpha(t,1) ...
%                f.alpha(t,2) ...
%                f.alpha(t,3) ...
%                f.alpha(t,4) ...
%                f.beta(t,1) ...
%                f.beta(t,2) ...
%                f.beta(t,3) ...
%                f.beta(t,4) ...
%                f.gamma(t,1) ...
%                f.gamma(t,2) ...
%                f.gamma(t,3) ...
%                f.gamma(t,4) ...
%                f.delta(t,1) ...
%                f.delta(t,2) ...
%                f.delta(t,3) ...
%                f.delta(t,4) ...
%                f.theta(t,1) ...
%                f.theta(t,2) ...
%                f.theta(t,3) ...
%                f.theta(t,4) ...
%             ];
        try
        row = [f.alpha(3,t) ...
               f.beta(1,t) ...
               f.beta(2,t) ...
               f.gamma(1,t) ...
               f.gamma(2,t) ...
               f.gamma(3,t) ...
               f.theta(1,t) ...
            ];
        catch f
            a=1;
        end
        observations = [observations ; row]; %#ok<AGROW>
        k = k+1;
     end
end
observations = zscore(observations);
features = [cell2table(response') array2table(observations)];
features.Properties.VariableNames = varNames;